name: Build Trigger build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: JDK ${{matrix.java-version}} on ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-java@v4
        name: Set up JDK ${{ matrix.java-version }} - ${{ matrix.os }}
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: mvn clean install